from PIL import Image
import numpy as np
from PIL import ImageChops
import matplotlib.pyplot as plt

im = Image.open("IMG20231017121105.jpg")
print("tryb", im.mode)
print("format", im.format)
print("rozmiar", im.size)

T = np.array(im)

t_r = T[:, :, 0]
im_r = Image.fromarray(t_r)
t_g = T[:, :, 1]
im_g = Image.fromarray(t_g)
t_b = T[:, :, 2]
im_b = Image.fromarray(t_b)

im2 = Image.merge('RGB', (im_r, im_g, im_b))

im_diff = ImageChops.difference(im, im2)

plt.figure(figsize=(32, 16))
plt.subplot(1, 3, 1)
plt.imshow(im)
plt.axis('off')
plt.subplot(1, 3, 2)
plt.imshow(im2, "gray")
plt.axis('off')
plt.subplot(1, 3 ,3)
plt.imshow(im_diff, "gray")
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.savefig('fig1.png')
plt.show()

r, g, b = im.split()

im3 = Image.merge('RGB', (r, b, g))
im3.save("im3.jpg")
im3.save("im3.png")

im3_jpg = Image.open("im3.jpg")
im3_png = Image.open("im3.png")
print("Tryb jpg:", im3_jpg.mode)
print("Tryb png:", im3_png.mode)

im3_diff = ImageChops.difference(im3_jpg, im3_png)

plt.figure(figsize=(32, 16))
plt.subplot(1, 3, 1)
plt.imshow(im3_png)
plt.axis('off')
plt.subplot(1, 3, 2)
plt.imshow(im3_jpg, "gray")
plt.axis('off')
plt.subplot(1, 3 ,3)
plt.imshow(im3_diff, "gray")
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.savefig('fig2.png')
plt.show()

img1 = Image.open("obraz1_1.jpg")
img2 = Image.open("obraz1_1.png")
img3 = Image.open("obraz1_1N.jpg")
img4 = Image.open("obraz1_1N.png")
img5 = Image.open("obraz1_2.jpg")
img6 = Image.open("obraz1_2.png")
img7 = Image.open("obraz1_2N.jpg")
img8 = Image.open("obraz1_2N.png")

imgdiff1 = ImageChops.difference(img1, img2)
imgdiff2 = ImageChops.difference(img3, img4)
imgdiff3 = ImageChops.difference(img5, img6)
imgdiff4 = ImageChops.difference(img7, img8)
# imgdiff1.show()
# imgdiff2.show()
# imgdiff3.show()
# imgdiff4.show()

print(img1.mode)
print(img2.mode)
print(img3.mode)
print(imgdiff1.mode)

plt.figure(figsize=(32, 16))
plt.subplot(4, 3, 1)
plt.imshow(img1, "gray")
plt.axis('off')
plt.subplot(4, 3, 2)
plt.imshow(img2, "gray")
plt.axis('off')
plt.subplot(4, 3, 3)
plt.imshow(imgdiff1, "gray")
plt.axis('off')
plt.subplot(4, 3, 4)
plt.imshow(img3, "gray")
plt.axis('off')
plt.subplot(4, 3, 5)
plt.imshow(img4, "gray")
plt.axis('off')
plt.subplot(4, 3, 6)
plt.imshow(imgdiff2, "gray")
plt.axis('off')
plt.subplot(4, 3, 7)
plt.imshow(img5, "gray")
plt.axis('off')
plt.subplot(4, 3, 8)
plt.imshow(img6, "gray")
plt.axis('off')
plt.subplot(4, 3, 9)
plt.imshow(imgdiff3, "gray")
plt.axis('off')
plt.subplot(4, 3, 10)
plt.imshow(img7, "gray")
plt.axis('off')
plt.subplot(4, 3, 11)
plt.imshow(img8, "gray")
plt.axis('off')
plt.subplot(4, 3, 12)
plt.imshow(imgdiff4, "gray")
plt.axis('off')
plt.subplots_adjust(wspace=0.05, hspace=0.05)
plt.savefig('fig3.png')
plt.show()